# Generated by Django 5.2.8 on 2025-11-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Іконка (FontAwesome)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=120, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.URLField(blank=True, verbose_name='URL зображення')),
                ('publication_date', models.DateField(verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='myblog.category', verbose_name='Категорія')),
                ('tag', models.ManyToManyField(blank=True, related_name='articles', to='myblog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ('-publication_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.CharField(max_length=120, verbose_name='Автор')),
                ('publication_date', models.DateField(verbose_name='Дата публікації')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ('-publication_date',),
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'publication_date'], name='myblog_arti_is_publ_6317cc_idx'),
        ),
    ]
