# Generated by Django 5.2.8 on 2025-11-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-publication_date',), 'permissions': [('change_own_comment', 'Can change own comment'), ('delete_own_comment', 'Can delete own comment'), ('delete_any_comment', 'Can delete any comment')], 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
    ]
